### PR TITLE
Add @return tags

### PR DESCRIPTION
**Pull request by Tjoosten**

### CODE REVIEW

**Comment by pietercolpaert** [comment]
It looks like you've indented all doc blocks too deep?

**Comment by Tjoosten** [comment]
How u mean @pietercolpaert

**Comment by pietercolpaert** [comment]
Ooh, you've used tabs instead of 4 spaces indent for the comments

```php
+	/**
+	 * @param $ec
+	 * @param $msg
+	 * @return mixed|void
+	 */
     function printError($ec, $msg){
```

**Comment by Tjoosten** [comment]
Indeed! is that wrong?

**Comment by pietercolpaert** [comment]
Yup! 4 spaces indent is PSR-2: http://www.php-fig.org/psr/psr-2/

**Comment by Tjoosten** [comment]
Ok now i need to figure out how what is spaces indent.

**Comment by Tjoosten** [comment]
@pietercolpaert  It is fixed now normally. Can u plz recheck it

**Pull request closed without merging**
