### PR TITLE
Changed to new id and .env changed to root directory

### PR DESCRIPTION
**Pull request by StanCallewaert**
The new id of a connection is changed (e.g. http://irail.be/connections/8812005/20160722T1642/IC2214).

Also the .env and .env.example files were moved to the root directory instead of the api directory.

Both of these changes were requested by @pietercolpaert in this PR: https://github.com/iRail/iRail/pull/191.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
### Are you sure the id is correct?

It looks to me only `$feedback['date']` is processed in the ID and not the datetime? And is it in the right format?

Furthermore: what timezone will this be in? Right now, in graph.spitsgids.be it's always in UTC

### .env

Looks great! Thanks!

**Comment by StanCallewaert** [comment]
`$feedback['date']` is the correct format (e.g. 20160722T1642) it is already processed by the post request. The timezone however is this one: `date_default_timezone_set('Europe/Brussels');`. Which makes a lot of sence to me because al the trains drive in this timezone.

**Comment by pietercolpaert** [comment]
Yeah, it does indeed make sense for the output, but for the identifier we
need to use the same identifier everywhere... Should we change the
identifier everywhere to Europe/brussels time?

Op zo 24 jul. 2016 15:57 schreef StanCallewaert <notifications@github.com>:

**Comment by pietercolpaert** [comment]
It indeed makes more sense. I've opened this issue: https://github.com/iRail/belgianrailgtfs2lc/issues/1 - It explains the problems we're currently facing. I will cut the knot tomorrow.

**Comment by pietercolpaert** [comment]
In meantime, I'll already merge this PR

**Pull request merged**
