### PR TITLE
Fix subtype decoding for 4 carriages trains

### PR DESCRIPTION
**Pull request by LaurentVB**
Hello 👋  
Reading source code, I realized this check was probably a copy-paste mistake as it didn't match the comment right above it.

I just discovered iRail after trying to use the realtime GTFS data of the SNCB/NMBS and missing the composition data. Thanks for the API and for making it open-source 🙏

### CODE REVIEW

**Review by Bertware — APPROVED** [review]
Nice catch!

**Comment by Bertware** [comment]
Thanks for the contribution, definitely looks like a copy-paste mistake as the switch case already supports 4 possible values.

**Comment by LaurentVB** [comment]
Cool. 
If that's of any interest to you, I'd love to contribute a bit to this api (even though my php skills are probably very rusty 😬)
Are there any parts or aspects that I could help with?

**Comment by Bertware** [comment]
Currently we're in a hurry to switch the source of the internal data to a different data source, but after that we'll work on actually making iRail independent of the NMBS internal APIs (as soon as their open data contains sufficient data). You can read more about this here: https://github.com/iRail/iRail/issues/466#issuecomment-1307063873

**Pull request merged**
