### PR TITLE
PR for #51

### PR DESCRIPTION
**Pull request by Tjoosten**
- Removed all the the php closing tags.
- Added docblocks to the functions. 
- Did some improvements to the code.
- replace `array()` with `[ ]`.

PR for #51 and more

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Sorry for the late reply: @Tjoosten is this [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) compliant? If we'd reindent the code (which I believe is necessary as well), I'd like to use standards :)

**Comment by Tjoosten** [comment]
Yes it is. If you want i can further build this out for u.

**Comment by pietercolpaert** [comment]
Would be more than welcome! I'll test whether there are regressions in the code next week and I'll merge this one soon :)

**Comment by Tjoosten** [comment]
Ok i will work then on the guzzle implementation.

**Pull request closed without merging**
