### PR TITLE
replace array() with [ ]

### PR DESCRIPTION
**Pull request by Tjoosten**
work on the migration to PSR-2. refer to #53 

Note to @pietercolpaert: Not tested.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Thanks @Tjoosten!

What do you mean with "speed up"? It's not required by PSR-2 to have `[]` instead of `array()` right? If so, can you direct me to the page where that's mentioned?

I'm not a very big fan of changing this everywhere as people with PHP5.3 (e.g., in ubuntu 12.04) will not be able to use that code

**Comment by Tjoosten** [comment]
Ok Speed up i mean. I want to do the checkboxes in issue report #53. 
I don't see anything about the arrays in the codestyling guides. But in my opinion this is better. Because PHP7 is coming. And PHP .3 only get security updates.

**Comment by pietercolpaert** [comment]
Not 100% in favour, but hey: you've already done the job so and it looks ok ;)

**Comment by Tjoosten** [comment]
And can i talk to you on gitter. I have reserached a new deploy management for this repo

**Pull request merged**
