### PR TITLE
Return logs as json array

### LINKED ISSUE #152: malformed JSON in logs
Hello, I don't know if the logs (http://api.irail.be/logs/#) issues should be reported here, but the JSON is not correct
capture

Not really a big issue, but annoying...

### PR DESCRIPTION
**Pull request by karel1980**
I got bored this afternoon. The encode/decode steps aren't strictly necessary, but I thought the overhead can be justified by the fact that we have some guarantees now that we won't return invalid json.

fixes #152

### CODE REVIEW

**Comment by karel1980** [comment]
failed or passed? StyleCI confusing the hell of out me. Also: if it failed, it doesn't seem to tell what failed, so I can't fix it.

image

**Comment by karel1980** [comment]
(test - is github eating my comments?) image

**Comment by karel1980** [comment]
test - github eating my comments?

**Comment by pietercolpaert** [comment]
Don't worry about styleci. Will fix the style myself later :)

**Comment by pietercolpaert** [comment]
Thanks Karel! Your PR is now in production!

**Comment by karel1980** [comment]
w00t

**Pull request merged**
