### PR TITLE
Quick fix for #81

### PR DESCRIPTION
**Pull request by Tjoosten**

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Did you test whether liveboard, vehicle, connections and stations still work?

**Comment by Tjoosten** [comment]
I'm working on this right now

**Comment by Tjoosten** [comment]
Return localhost:8000/vehicle.php. 
```
<error code="400">
id not set. Please review your request and add the right parameters
</error>
```

return localhost:8000/connections.php
```
<error code="400">
from not set. Please review your request and add the right parameters
</error>
```

return localhost:8000/liveboard.php

```
<error code="400">
station not set. Please review your request and add the right parameters
</error>
```

return localhost:8000/stations.php 
```
data payload
```

So i think it's working

**Comment by pietercolpaert** [comment]
I think you should at least try setting a vehicle, from and to pair for connections and a station for liveboard... right? Otherwise the structs are never used ;)

**Comment by Tjoosten** [comment]
It works

**Pull request merged**
