### PR TITLE
Release current Development branch (updated vehicle source #332, PSR-4, tests, train types and numbers)

### LINKED ISSUE #332: Use mobile API endpoint instead of parsing the NMBS website for vehicle information
At this moment, we're parsing the NMBS website for vehicle information. Every now and then this page isn't available for a few seconds, and when the NMBS updates their website, this endpoint will break completely.

Therefore, we should switch to the mobile API, like we did for liveboards and routes. The endpoint for the following requests is http://www.belgianrail.be/jp/sncb-nmbs-routeplanner/mgate.exe.

To overcome the need for a journey ID, we can lookup the journey ID by the train name:

`{"auth":{"aid":"sncb-mobi","type":"AID"},"client":{"id":"SNCB","name":"NMBS","os":"Android 7.0","type":"AND","ua":"SNCB/302240 (Android_7.0) Dalvik/2.1.0 (Linux; U; Android 7.0; HTC One Build/NRD90M)","v":302240},"formatted":false,"lang":"nld","svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyMatch","req":{"date":"20171121","input":"ic537","jnyFltrL":[{"mode":"BIT","type":"PROD","value":"10101010000000"}]}}],"ver":"1.11"}`

From this response we can obtain a journey ID, which can be used to obtain the vehicle:

```
{"auth":{"aid":"sncb-mobi","type":"AID"},"client":{"id":"SNCB","name":"NMBS","os":"Android 5.0.2","type":"AND","ua":"SNCB/302132 (Android_5.0.2) Dalvik/2.1.0 (Linux; U; Android 5.0.2; HTC One Build/LRX22G)","v":302132},"lang":"nld",
"svcReqL":[{"cfg":{"polyEnc":"GPA"},"meth":"JourneyDetails","req":{"jid":"1|297|0|80|21112017","getTrainComposition":false}}],"ver":"1.11","formatted":false}
```

Once switched to this data, the vehicle endpoint should be faster, have better availability, and be future-proof

### LINKED ISSUE #379: Uncaught errors in Vehicle endpoint
```
PHP Fatal error:  Uncaught Error: Call to a member function getElementByTagName() on null in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php:139"
 "Stack trace:"
"#0 /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php(66): vehicleinformation::getData(Object(simple_html_dom), 'EN', 'false', Array, '110419', 'BE.NMBS.S11995', NULL)"
"#1 /var/www/api.irail.be/api/data/DataRoot.php(68): vehicleinformation::fillDataRoot(Object(DataRoot), Object(VehicleinformationRequest))"
"#2 /var/www/api.irail.be/api/APICall.php(84): DataRoot->fetchData(Object(VehicleinformationRequest))"
"#3 /var/www/api.irail.be/api/vehicle.php(11): APICall->executeCall()"
"#4 {main}"
"  thrown in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php on line 139"
```

```
PHP Fatal error:  Uncaught Error: Call to a member function format() on boolean in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php:100
Stack trace:
#0 /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php(31): vehicleinformation::getServerData('P1234', '', 'EN')
#1 /var/www/api.irail.be/api/data/DataRoot.php(68): vehicleinformation::fillDataRoot(Object(DataRoot), Object(VehicleinformationRequest))
#2 /var/www/api.irail.be/api/APICall.php(84): DataRoot->fetchData(Object(VehicleinformationRequest))
#3 /var/www/api.irail.be/api/vehicle.php(11): APICall->executeCall()
#4 {main}
  thrown in /var/www/api.irail.be/api/data/NMBS/vehicleinformation.php on line 100

```

### LINKED ISSUE #406: get train type (Sx,IC,L) and train number
In the API data I see train type and train number as one string like:

`<vehicle URI="http://irail.be/vehicle/S521880">BE.NMBS.S521880</vehicle>`

No problem for IC and L trains but not clear for S trains. This case the train type is S52 and train number is 1880. Suggested solution:

`<vehicle URI="http://irail.be/vehicle/S521880" type="S52" number="1880" operator="BE.NMBS">BE.NMBS.S521880</vehicle>`

I need this for my screen saver project [https://github.com/tom-2015/RailtimeScreenSaver](https://github.com/tom-2015/RailtimeScreenSaver). Right now I'm parsing NMBS html but I'm afraid one day they will change or put it down.

### PR DESCRIPTION
**Pull request by Bertware**
This pull request will release a couple of new features and bug fixes:

- #414 Irail has been restructured to use PSR-4 namespaces. This fixes the hassle with imports, and makes it easy to test the software. Some unit tests have been written, as well as integration tests for liveboards, connections and vehicles. New features should be tested from now on.
- #415 The vehicle source has been updated from the NMBS website to the internal NMBS API. *Needs to be tested in staging before merging.* This fixes #332. Integration tests have been written to ensure correct behaviour.
- #413 Train type and number are now included in the vehicle and liveboard endpoint. Fixes #406 

Also fixes #379

### CODE REVIEW

**Comment by Bertware** [comment]
@jncn @ChristopheVersieux We got automated testing now (yay!) which caught quite some bugs, but you still might be interested in testing your apps using staging.api.irail.be. The vehicle endpoint now has an "arrived" field, and every vehicleinfo object (json) or vehicle tag (xml) is now identical throughout the entire API. They now include type and number, as well as the short name in every result.

No fields were removed.

**Comment by jncn** [comment]
Nice work @Bertware, thanks a lot! I don't have much time currently, but will have a look at the changes in a bit.

**Comment by Bertware** [comment]
@jncn I'm not releasing this before August 19th, so you have some time. I have tested with my own app and it works without issues (only needed an update to make use of the new arrived, train.type and train.number), I think the most important thing would be that your parser doesn't fail on added XML attributes.

**Comment by Bertware** [comment]
@jncn were you able to test this? I'm planning to release either tonight or tomorrow (at a calm time, i'm expecting a few minutes downtime)

**Comment by jncn** [comment]
Not yet unfortunately, I'm on a holiday currently and didn't have the time before...

**Comment by Bertware** [comment]
I'll release, test and roll back if needed

**Comment by Bertware** [comment]
No issues with Railer (xml) and HyperRail (json), enjoy your vacation and the new data @jncn! There were only 2 minutes of downtime during the release (thanks to the staging environment). @pietercolpaert from now on we are independent from the old NMBS website, and integration/regression tests safeguard the iRail code quality.

**Pull request merged**
